/**
 * Pipedrive integration for the SetupWizard onboarding flow. Builds on the
 * official `pipedrive` SDK (used elsewhere in the codebase) and the field
 * map generated by scripts/fetch-pipedrive-fields.ts.
 *
 * Public API:
 *   - findOrCreatePerson(payload)        → returns person_id
 *   - createOnboardingLead(payload, personId) → returns lead_id (UUID string)
 *   - attachOnboardingNote(leadId, html)  → no-op return on success
 *   - createFollowUpActivity(leadId, personId, payload) → optional best-effort
 *
 * Errors are surfaced; the caller decides whether they fail the request
 * (Person + Lead are critical) or are logged and swallowed (Note, Activity
 * are nice-to-have).
 */

import Pipedrive from "pipedrive"
import type { OnboardingPayload } from "../types/onboardingTypes.js"
import { dealFieldKey, dealOptionId, personFieldKey, type DealFieldId } from "./pipedriveFieldMap.js"
import { Channel } from "../config/pipedriveConfig.js"
// Pipedrive's `channel` field on Leads is a single-option enum and the API
// rejects string labels — it requires the numeric option_id. resolveCustomFieldId
// looks up that id by label from /leadFields and caches the result.
import { resolveCustomFieldId } from "./pipedriveLib.js"

function getApiClient() {
  const token = process.env.PIPEDRIVE_API_TOKEN
  if (!token) throw new Error("PIPEDRIVE_API_TOKEN is not set")
  const client = new Pipedrive.ApiClient()
  client.authentications.api_key.apiKey = token
  return client
}

function getDefaultOwnerId(): number | undefined {
  const raw = process.env.PIPEDRIVE_DEFAULT_OWNER_ID
  if (!raw) return undefined
  const id = Number(raw)
  return Number.isFinite(id) ? id : undefined
}

/* =====================================================================
 * Person: find by email, otherwise create
 * ===================================================================== */

export interface PersonResult {
  id: number
  created: boolean
}

export async function findOrCreatePerson(payload: OnboardingPayload): Promise<PersonResult> {
  const client = getApiClient()
  const personsApi = new Pipedrive.PersonsApi(client)
  const { contact } = payload

  // exact-match search by email — Pipedrive returns the first matching item
  const search = await personsApi.searchPersons(contact.email, {
    fields: "email",
    exactMatch: true,
    limit: 1,
  })
  const items = (search?.data?.items as Array<{ item: { id: number } }> | undefined) ?? []
  if (items.length > 0 && items[0]?.item?.id) {
    return { id: items[0].item.id, created: false }
  }

  // Create new Person. We label phone as "Mobile" — same number doubles as
  // WhatsApp; manager can switch the label per-conversation if needed.
  const personPayload: Record<string, unknown> = {
    name: contact.name,
    email: [{ value: contact.email, primary: true, label: "work" }],
    phone: [{ value: contact.phone_e164, primary: true, label: "Mobile" }],
    [personFieldKey("countryCode")]: contact.country_code,
  }

  const created = await personsApi.addPerson(personPayload as never)
  if (!created?.data?.id) {
    throw new Error("Failed to create person — Pipedrive returned no id")
  }
  return { id: created.data.id, created: true }
}

/* =====================================================================
 * Lead: create with all custom fields populated and option_ids resolved
 * ===================================================================== */

interface LeadResult {
  id: string // Pipedrive Lead ids are UUID strings, not numeric like Deal ids
}

export async function createOnboardingLead(payload: OnboardingPayload, personId: number): Promise<LeadResult> {
  const client = getApiClient()
  const leadsApi = new Pipedrive.LeadsApi(client)
  const { contact, step1, step2, step3, step4, step5, step6, step7, step8, step9, notes, meta } = payload

  // Map step-payload values to Pipedrive option_ids. Skip null values so we
  // don't send `field: null` (Pipedrive treats that as "clear field" rather
  // than "not provided").
  const customFields: Record<string, unknown> = {}
  const setOption = (id: DealFieldId, value: number | null) => {
    const optionId = dealOptionId(id, value)
    if (optionId !== null) customFields[dealFieldKey(id)] = optionId
  }

  setOption("applicantType", step1.value)
  setOption("mainGoal", step2.value)
  setOption("licenseType", step3.value)
  setOption("businessActivity", step4.category)
  setOption("companyStructure", step5.value)
  setOption("wantsResidency", step6.value)
  setOption("bankAccount", step7.value)
  setOption("currentlyInUae", step8.value)
  setOption("launchTimeline", step9.value)

  // Text fields. Build a single Message string that includes the user's
  // free-text comment plus any "Other" clarifications from steps 1 and 4.
  const messageParts: string[] = []
  if (step1.value === 4 && step1.other_text) messageParts.push(`[Applicant — Other] ${step1.other_text}`)
  if (step4.category === 8 && step4.description) messageParts.push(`[Activity — Other] ${step4.description}`)
  if (notes && notes.trim().length > 0) {
    if (messageParts.length > 0) messageParts.push("---")
    messageParts.push(notes.trim())
  }
  if (messageParts.length > 0) customFields[dealFieldKey("message")] = messageParts.join("\n")

  if (meta.source_url) customFields[dealFieldKey("url")] = meta.source_url
  if (meta.utm_source) customFields[dealFieldKey("utmSource")] = meta.utm_source
  if (meta.utm_campaign) customFields[dealFieldKey("utmCampaign")] = meta.utm_campaign

  const ownerId = getDefaultOwnerId()
  const channelOptionId = await resolveCustomFieldId("channel", Channel.WEB_FORMS)
  const titleDate = (meta.submitted_at || new Date().toISOString()).slice(0, 10)
  const leadPayload: Record<string, unknown> = {
    title: `Business Setup — ${contact.name} — ${titleDate}`,
    person_id: personId,
    was_seen: false,
    channel: channelOptionId,
    ...(ownerId !== undefined ? { owner_id: ownerId } : {}),
    ...customFields,
  }

  const created = await leadsApi.addLead(leadPayload as never)
  const id = created?.data?.id
  if (!id || typeof id !== "string") {
    throw new Error("Failed to create lead — Pipedrive returned no id")
  }
  return { id }
}

/* =====================================================================
 * Note attached to a Lead
 * ===================================================================== */

export async function attachOnboardingNote(leadId: string, content: string): Promise<void> {
  const client = getApiClient()
  const notesApi = new Pipedrive.NotesApi(client)
  await notesApi.addNote({ lead_id: leadId, content } as never)
}

/* =====================================================================
 * Activity ("First call ...") with deadline +1 business day
 * ===================================================================== */

function nextBusinessDay(from: Date): Date {
  const d = new Date(from)
  d.setUTCDate(d.getUTCDate() + 1)
  // Skip Saturday (6) → Monday; Sunday (0) → Monday
  const dow = d.getUTCDay()
  if (dow === 6) d.setUTCDate(d.getUTCDate() + 2)
  else if (dow === 0) d.setUTCDate(d.getUTCDate() + 1)
  return d
}

export async function createFollowUpActivity(leadId: string, personId: number, payload: OnboardingPayload): Promise<void> {
  const client = getApiClient()
  const activitiesApi = new Pipedrive.ActivitiesApi(client)
  const { contact } = payload
  const ownerId = getDefaultOwnerId()
  const dueDate = nextBusinessDay(new Date()).toISOString().slice(0, 10)

  await activitiesApi.addActivity({
    subject: `First call with ${contact.name}`,
    type: "call",
    lead_id: leadId,
    person_id: personId,
    due_date: dueDate,
    note: "New onboarding form submission. Review the attached summary note and call within 24h.",
    ...(ownerId !== undefined ? { user_id: ownerId } : {}),
  } as never)
}
